[build]
  publish = "frontend/build"
  command = "cd frontend && npm ci && npm run build"
  functions = "netlify/functions"

[build.environment]
  REACT_APP_DEMO_MODE = "false"
  REACT_APP_API_URL = "/.netlify/functions"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_DEMO_MODE = "false"
  REACT_APP_API_URL = "/.netlify/functions"
  CI = "false"