"""Initial PostgreSQL migration

Revision ID: d4b21938cb6e
Revises: 
Create Date: 2025-06-19 15:41:59.867515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b21938cb6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_application_types_id'), 'application_types', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=20), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('application_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_type_id'], ['application_types.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.String(length=200), nullable=True),
    sa.Column('construction_type', sa.String(length=100), nullable=True),
    sa.Column('primary_use', sa.String(length=100), nullable=True),
    sa.Column('structure', sa.String(length=100), nullable=True),
    sa.Column('floors', sa.String(length=50), nullable=True),
    sa.Column('max_height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('building_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('owner_kana', sa.String(length=100), nullable=True),
    sa.Column('owner_zip', sa.String(length=10), nullable=True),
    sa.Column('owner_address', sa.Text(), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('joint_name', sa.String(length=100), nullable=True),
    sa.Column('joint_kana', sa.String(length=100), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=True),
    sa.Column('client_staff', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('contract_price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('estimate_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('construction_cost', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('juchu_note', sa.Text(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('settlement_staff', sa.String(length=100), nullable=True),
    sa.Column('settlement_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('settlement_note', sa.Text(), nullable=True),
    sa.Column('has_permit_application', sa.Boolean(), nullable=True),
    sa.Column('has_inspection_schedule', sa.Boolean(), nullable=True),
    sa.Column('has_foundation_plan', sa.Boolean(), nullable=True),
    sa.Column('has_hardware_plan', sa.Boolean(), nullable=True),
    sa.Column('has_invoice', sa.Boolean(), nullable=True),
    sa.Column('has_energy_calculation', sa.Boolean(), nullable=True),
    sa.Column('has_settlement_data', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_financials_id'), 'financials', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('reinforcement_scheduled', sa.Date(), nullable=True),
    sa.Column('reinforcement_actual', sa.Date(), nullable=True),
    sa.Column('interim_scheduled', sa.Date(), nullable=True),
    sa.Column('interim_actual', sa.Date(), nullable=True),
    sa.Column('completion_scheduled', sa.Date(), nullable=True),
    sa.Column('completion_actual', sa.Date(), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('inspection_result', sa.String(length=100), nullable=True),
    sa.Column('corrections', sa.Text(), nullable=True),
    sa.Column('final_report_date', sa.Date(), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('has_permit_returned', sa.Boolean(), nullable=True),
    sa.Column('has_report_sent', sa.Boolean(), nullable=True),
    sa.Column('has_items_confirmed', sa.Boolean(), nullable=True),
    sa.Column('change_memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('land_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('city_plan', sa.String(length=100), nullable=True),
    sa.Column('zoning', sa.String(length=100), nullable=True),
    sa.Column('fire_zone', sa.String(length=100), nullable=True),
    sa.Column('slope_limit', sa.String(length=100), nullable=True),
    sa.Column('setback', sa.String(length=100), nullable=True),
    sa.Column('other_buildings', sa.Text(), nullable=True),
    sa.Column('landslide_alert', sa.String(length=100), nullable=True),
    sa.Column('flood_zone', sa.String(length=100), nullable=True),
    sa.Column('tsunami_zone', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_financials_id'), table_name='financials')
    op.drop_table('financials')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_application_types_id'), table_name='application_types')
    op.drop_table('application_types')
    # ### end Alembic commands ###